### ISSUE TITLE
question about process audio

### ISSUE THREAD

**Issue by softlipang** [cristinalunaj/MMEmotionRecognition#1]
I don't know how to process the audio data, please update "process_audio.py ",  thank you very much.

**Comment by cristinalunaj** [comment]
Hi! I am still uploading some of the files and docs, probably it does not work because you haven't installed the FFMPEG library (https://www.ffmpeg.org/download.html#build-linux). 
If this is not the error, please copy the error that appears in the console to know better how to solve it. Thanks!

**Comment by cristinalunaj** [comment]
Nice! I have uploaded all the files now in case you want to continue with the experiments. Let me know if you find any other error :) thanks!

**Comment by ioctl-user** [comment]
In the README file preprocessing script path is MMEmotionRecognition/src/Audio/FineTuningWav2Vec/process_audio.py , but it has another path.

**Comment by cristinalunaj** [comment]
Thanks, you are right, I have changed the path, it should be on the correct path now.
